// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs8LSeMfjAjJz3Ui9q4bl6JBpH_suqlwA',
    appId: '1:662468768294:web:7294a309c15fed3fd46ce7',
    messagingSenderId: '662468768294',
    projectId: 'macapp-40ec0',
    authDomain: 'macapp-40ec0.firebaseapp.com',
    storageBucket: 'macapp-40ec0.appspot.com',
    measurementId: 'G-N1S8HYEYEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7K8wCEIRSxP4DCrKIXQ3XYOtisHuyTtU',
    appId: '1:662468768294:android:5040959d2e9d9429d46ce7',
    messagingSenderId: '662468768294',
    projectId: 'macapp-40ec0',
    storageBucket: 'macapp-40ec0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-ZCIpW0f5lOGWofB4wd3Q5bfryGTyt5Q',
    appId: '1:662468768294:ios:9aa33c6d99cd6c7fd46ce7',
    messagingSenderId: '662468768294',
    projectId: 'macapp-40ec0',
    storageBucket: 'macapp-40ec0.appspot.com',
    iosClientId:
        '662468768294-eapiseds2jh2nsqn0p64kh1fihs73o68.apps.googleusercontent.com',
    iosBundleId: 'com.example.mda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-ZCIpW0f5lOGWofB4wd3Q5bfryGTyt5Q',
    appId: '1:662468768294:ios:9aa33c6d99cd6c7fd46ce7',
    messagingSenderId: '662468768294',
    projectId: 'macapp-40ec0',
    storageBucket: 'macapp-40ec0.appspot.com',
    iosClientId:
        '662468768294-eapiseds2jh2nsqn0p64kh1fihs73o68.apps.googleusercontent.com',
    iosBundleId: 'com.example.mda',
  );
}
